using System;
using System.Collections;
using UnityEngine;

/// <summary>
/// Manages the player's ultimate ability — a separate gauge-based system
/// that fires a room-wide damage effect when fully charged by hitting enemies.
///
/// The ultimate is generated by Gemini (SpellTier.Ultimate) but does NOT live in
/// the Grimoire loadout. Place on the player GameObject.
/// </summary>
public class UltimateAbility : MonoBehaviour
{
    public static UltimateAbility Instance { get; private set; }

    private SpellData _spell;
    private int _hitCount;
    private int _requiredHits = 40;

    public SpellData Spell        => _spell;
    public int       HitCount     => _hitCount;
    public int       RequiredHits => _requiredHits;
    public float     GaugePct     => _requiredHits > 0 ? (float)_hitCount / _requiredHits : 0f;
    public bool      IsReady      => _spell != null && _hitCount >= _requiredHits;

    public event Action OnGaugeChanged;
    public event Action OnBecameReady;

    private void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(gameObject); return; }
        Instance = this;
        DontDestroyOnLoad(gameObject);
    }

    private void OnDestroy()
    {
        if (Instance == this) Instance = null;
    }

    // ── Spell assignment ──────────────────────────────────────────────────────

    public void SetSpell(SpellData spell)
    {
        _spell        = spell;
        _requiredHits = spell != null ? CalcRequiredHits(spell) : 40;
        _hitCount     = Mathf.Min(_hitCount, _requiredHits);
        OnGaugeChanged?.Invoke();
    }

    /// <summary>Required hits scale with spell power — stronger ultimates need more hits (30–60).</summary>
    private static int CalcRequiredHits(SpellData spell)
    {
        float t = Mathf.InverseLerp(40f, 80f, spell.damage);
        return Mathf.RoundToInt(Mathf.Lerp(30f, 60f, t));
    }

    // ── Hit registration ──────────────────────────────────────────────────────

    public void RegisterHit()
    {
        if (IsReady || _spell == null) return;
        _hitCount = Mathf.Min(_hitCount + 1, _requiredHits);
        if (_hitCount >= _requiredHits)
            OnBecameReady?.Invoke();
        OnGaugeChanged?.Invoke();
    }

    // ── Firing ────────────────────────────────────────────────────────────────

    public void TryFire()
    {
        if (!IsReady) return;
        _hitCount = 0;
        OnGaugeChanged?.Invoke();
        SFXManager.Instance?.PlayUltimateCast();
        StartCoroutine(FireRoutine());
    }

    private IEnumerator FireRoutine()
    {
        // Dramatic flash + slow-mo
        yield return StartCoroutine(UltimateFlash());

        // Damage all enemies in a wide room radius (60% of their max HP)
        const float RoomRadius = 55f;
        Collider2D[] hits = Physics2D.OverlapCircleAll(transform.position, RoomRadius,
                                                        ProjectileHandler.EnemyMask);
        foreach (var col in hits)
        {
            var h = col.GetComponent<Health>();
            if (h == null || h.IsDead) continue;
            h.TakeDamage(h.Max * 0.60f);
        }

        // Shockwave visual
        yield return StartCoroutine(ShockwaveEffect());
    }

    // ── Visual effects ────────────────────────────────────────────────────────

    private IEnumerator UltimateFlash()
    {
        var flashGO = new GameObject("UltFlash");
        var cv      = flashGO.AddComponent<Canvas>();
        cv.renderMode   = RenderMode.ScreenSpaceOverlay;
        cv.sortingOrder = 999;
        flashGO.AddComponent<UnityEngine.UI.CanvasScaler>();
        var img         = flashGO.AddComponent<UnityEngine.UI.Image>();
        img.color       = new Color(1f, 0.85f, 0.2f, 0.75f);
        img.raycastTarget = false;

        // More lightning strikes
        for (int i = 0; i < 8; i++) SpawnLightningStrike();

        // Big radial burst from player
        Color spellColor = _spell != null
            ? ProjectileHandler.GetSpellColor(_spell)
            : new Color(1f, 0.85f, 0.2f);
        for (int i = 0; i < 24; i++)
        {
            float angle = i * Mathf.PI * 2f / 24f;
            var   dir   = new Vector2(Mathf.Cos(angle), Mathf.Sin(angle));
            StartCoroutine(DriftParticle(transform.position, dir * 10f, spellColor, 0.5f));
        }

        // Camera shake
        StartCoroutine(ShakeCamera(0.35f, 0.45f));

        Time.timeScale = 0.12f;

        float elapsed = 0f;
        while (elapsed < 0.25f)
        {
            elapsed += Time.unscaledDeltaTime;
            if (img != null)
                img.color = new Color(1f, 0.85f, 0.2f, Mathf.Lerp(0.75f, 0f, elapsed / 0.25f));
            yield return null;
        }
        if (flashGO != null) Destroy(flashGO);

        yield return new WaitForSecondsRealtime(0.35f);
        if (!PauseManager.IsPaused) Time.timeScale = 1f;
    }

    private IEnumerator ShakeCamera(float magnitude, float duration)
    {
        Camera cam = Camera.main;
        if (cam == null) yield break;

        Vector3 origin = cam.transform.localPosition;
        float elapsed  = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.unscaledDeltaTime;
            float dampen = 1f - (elapsed / duration);
            float ox = UnityEngine.Random.Range(-1f, 1f) * magnitude * dampen;
            float oy = UnityEngine.Random.Range(-1f, 1f) * magnitude * dampen;
            cam.transform.localPosition = origin + new Vector3(ox, oy, 0f);
            yield return null;
        }
        cam.transform.localPosition = origin;
    }

    private IEnumerator ShockwaveEffect()
    {
        // 5 staggered expanding rings
        for (int i = 0; i < 5; i++)
            StartCoroutine(ExpandRing(i * 0.08f));

        // 24 radial drift particles (two layers — fast close, slow far)
        Color spellColor = _spell != null
            ? ProjectileHandler.GetSpellColor(_spell)
            : new Color(1f, 0.85f, 0.2f);
        for (int i = 0; i < 24; i++)
        {
            float angle = i * Mathf.PI * 2f / 24f;
            var   dir   = new Vector2(Mathf.Cos(angle), Mathf.Sin(angle));
            float speed = i % 2 == 0 ? 8f : 4f;
            StartCoroutine(DriftParticle(transform.position, dir * speed, spellColor, 0.9f));
        }

        yield return new WaitForSeconds(0.9f);
    }

    private IEnumerator ExpandRing(float delay)
    {
        if (delay > 0f) yield return new WaitForSeconds(delay);

        Color ringColor = _spell != null
            ? ProjectileHandler.GetSpellColor(_spell)
            : new Color(1f, 0.85f, 0.2f);

        const float MaxRadius = 60f;
        const float Duration  = 0.7f;
        const int   Segs      = 48;

        var go = new GameObject("UltRing");
        var lr = go.AddComponent<LineRenderer>();
        lr.useWorldSpace    = true;
        lr.loop             = true;
        lr.material         = HitEffectSpawner.GetAdditiveParticleMaterial();
        lr.sortingLayerName = "Entities";
        lr.sortingOrder     = 300;
        lr.positionCount    = Segs;

        float t = 0f;
        while (t < Duration)
        {
            t += Time.deltaTime;
            float frac  = t / Duration;
            float r     = MaxRadius * frac;
            float alpha = Mathf.Lerp(1f, 0f, frac);
            float w     = Mathf.Lerp(0.4f, 0.04f, frac);
            Color c     = new Color(ringColor.r, ringColor.g, ringColor.b, alpha);
            lr.startColor = c; lr.endColor = c;
            lr.startWidth = w; lr.endWidth = w;
            for (int i = 0; i < Segs; i++)
            {
                float ang = i * Mathf.PI * 2f / Segs;
                lr.SetPosition(i, new Vector3(
                    transform.position.x + Mathf.Cos(ang) * r,
                    transform.position.y + Mathf.Sin(ang) * r, 0f));
            }
            yield return null;
        }
        if (go != null) Destroy(go);
    }

    private static IEnumerator DriftParticle(Vector3 origin, Vector2 vel, Color color, float lifetime)
    {
        var go = new GameObject("UltPart");
        go.transform.position = origin;
        var sr = go.AddComponent<SpriteRenderer>();
        sr.sortingLayerName = "Entities";
        sr.sortingOrder     = 299;

        var tex = new Texture2D(1, 1, TextureFormat.RGBA32, false);
        tex.SetPixel(0, 0, Color.white);
        tex.Apply();
        sr.sprite = Sprite.Create(tex, new Rect(0, 0, 1, 1), new Vector2(0.5f, 0.5f), 1f);
        go.transform.localScale = Vector3.one * 0.3f;

        float t = 0f;
        while (t < lifetime && go != null)
        {
            t += Time.deltaTime;
            go.transform.position  += (Vector3)(vel * Time.deltaTime);
            sr.color = new Color(color.r, color.g, color.b, Mathf.Lerp(1f, 0f, t / lifetime));
            yield return null;
        }
        if (go != null) Destroy(go);
    }

    private void SpawnLightningStrike()
    {
        Camera cam = Camera.main;
        if (cam == null) return;
        float normX = UnityEngine.Random.Range(0.1f, 0.9f);
        Vector3 top    = cam.ViewportToWorldPoint(new Vector3(normX, 1.1f, cam.nearClipPlane + 1f));
        Vector3 bottom = cam.ViewportToWorldPoint(new Vector3(normX + UnityEngine.Random.Range(-0.15f, 0.15f), -0.1f, cam.nearClipPlane + 1f));
        top.z = bottom.z = 0f;

        var go = new GameObject("UltLightning");
        var lr = go.AddComponent<LineRenderer>();
        lr.useWorldSpace    = true;
        lr.positionCount    = 2;
        lr.SetPosition(0, top);
        lr.SetPosition(1, bottom);
        lr.startWidth       = 0.14f;
        lr.endWidth         = 0.05f;
        Color bolt          = new Color(1f, 0.95f, 0.4f, 1f);
        lr.startColor       = bolt;
        lr.endColor         = bolt;
        lr.material         = HitEffectSpawner.GetAdditiveParticleMaterial();
        lr.sortingLayerName = "Entities";
        lr.sortingOrder     = 998;

        StartCoroutine(FadeLightning(lr, bolt));
    }

    private IEnumerator FadeLightning(LineRenderer lr, Color c)
    {
        float t = 0f;
        while (t < 0.3f)
        {
            t += Time.unscaledDeltaTime;
            float a = Mathf.Lerp(1f, 0f, t / 0.3f);
            lr.startColor = new Color(c.r, c.g, c.b, a);
            lr.endColor   = new Color(c.r, c.g, c.b, a);
            yield return null;
        }
        if (lr != null) Destroy(lr.gameObject);
    }
}
